from enum import Enum
from typing import List, Optional
from pydantic import BaseModel, Field

class ConnectorType(str, Enum):
    CCS2 = "CCS2"
    Type2 = "Type2"
    CHAdeMO = "CHAdeMO"
    NACS = "NACS"
    GBT = "GBT"
    MCS = "MCS"

    @classmethod
    def from_string(cls, value: str) -> "ConnectorType":
        normalized = value.strip().upper()
        if normalized in ["TYPE 2", "MENNEKES", "TYPE2"]:
            return cls.Type2
        if normalized in ["CCS 2", "CCS COMBO 2", "CCS2"]:
            return cls.CCS2
        if normalized in ["TESLA", "NACS"]:
            return cls.NACS
        if normalized in ["CHADEMO", "CHA DE MO"]:
            return cls.CHAdeMO
        if normalized in ["GB/T", "GBT"]:
            return cls.GBT
        if normalized in ["MCS", "MEGAWATT"]:
            return cls.MCS
        return cls.CCS2

class ChargerInput(BaseModel):
    charger_id: str = Field(..., description="Unique charger identifier or UUID")
    identifier: str = Field(..., description="Bay label or charger identifier, e.g. BAY-01")
    connector: str = Field(..., description="Connector standard string, e.g. CCS2, NACS, Type2")
    power_kw: float = Field(..., ge=0, description="Rated peak power in kW")
    tariff: Optional[float] = Field(None, description="Price per kWh if available")

class StationInput(BaseModel):
    station_id: str = Field(..., description="Station UUID")
    name: str = Field(..., description="Station display name")
    address: Optional[str] = Field(None, description="Physical address")
    latitude: float = Field(..., ge=-90, le=90, description="Latitude")
    longitude: float = Field(..., ge=-180, le=180, description="Longitude")
    distance_km: Optional[float] = Field(0.0, ge=0, description="Distance from driver in km")
    chargers: List[ChargerInput] = Field(default_factory=list, description="List of chargers at this station")

class VehicleInput(BaseModel):
    vehicle_id: str = Field(..., description="Vehicle UUID")
    make: str = Field(..., description="Manufacturer, e.g. Tesla, Hyundai")
    model: str = Field(..., description="Model, e.g. Model 3, Ioniq 5")
    connector: str = Field(..., description="Vehicle connector standard, e.g. NACS, CCS2")
    battery_capacity_kwh: float = Field(..., gt=0, description="Usable battery capacity in kWh")
    max_charge_rate_kw: float = Field(..., gt=0, description="Max accepted charge rate in kW")
    license_plate: Optional[str] = Field(None, description="Optional vehicle license plate")

class ChargerCompatibilityDetail(BaseModel):
    charger_id: str
    identifier: str
    connector: str
    power_kw: float
    is_compatible: bool
    effective_power_kw: float
    estimated_charge_time_minutes: Optional[float] = None
    estimated_charge_time_formatted: Optional[str] = None

class AlternativeStationSuggestion(BaseModel):
    station_id: str
    name: str
    address: Optional[str] = None
    distance_km: float
    compatibility_score: int
    best_power_kw: float
    estimated_charge_time_formatted: Optional[str] = None
    reason: str

class CompatibilityRequest(BaseModel):
    vehicle: VehicleInput
    target_station: StationInput
    candidate_alternative_stations: List[StationInput] = Field(
        default_factory=list,
        description="Optional list of nearby stations to evaluate as alternatives if target is incompatible"
    )

class CompatibilityResponse(BaseModel):
    is_compatible: bool
    compatibility_score: int = Field(..., ge=0, le=100, description="0 to 100 compatibility score")
    best_charger_id: Optional[str] = None
    effective_charging_power_kw: float = 0.0
    estimated_charge_time_minutes: Optional[float] = None
    estimated_charge_time_formatted: Optional[str] = None
    chargers: List[ChargerCompatibilityDetail] = Field(default_factory=list)
    warnings: List[str] = Field(default_factory=list)
    suggested_alternatives: List[AlternativeStationSuggestion] = Field(default_factory=list)
    ai_insight: Optional[str] = Field(None, description="Natural language summary generated by the AI agent")

class BatchCompatibilityRequest(BaseModel):
    vehicle: VehicleInput
    stations: List[StationInput]

class BatchStationScore(BaseModel):
    station_id: str
    name: str
    distance_km: float
    is_compatible: bool
    compatibility_score: int
    effective_power_kw: float
    estimated_charge_time_formatted: Optional[str] = None
    chargers: List[ChargerCompatibilityDetail]

class BatchCompatibilityResponse(BaseModel):
    vehicle_summary: str
    stations: List[BatchStationScore]
