using Domain.Common;
using Domain.Enums;
using Domain.Users;

namespace Domain.Entities;

/// <summary>
/// Represents a slot booking on a physical charger unit .
///
/// Key design points:
/// <list type="bullet">
///   <item><c>DriverId</c> is <b>nullable</b> — a <c>null</c> value means an on-site
///   walk-in customer admitted by station staff .</item>
///   <item><c>VehicleId</c> is nullable — walk-ins have no registered vehicle profile.</item>
///   <item><c>ReservationQRCode</c> is set by the application layer after a signed
///   token is generated; it is never constructed inside the domain.</item>
///   <item>Double-booking prevention is enforced at the database level via a
///   PostgreSQL GiST exclusion constraint on <c>(ChargerId, tsrange(StartTime, EndTime))</c>
///   .</item>
///   <item>Advance wallet deduction happens in the application service before calling
///   <see cref="Create"/>; the amount is recorded here for invoice reconciliation.</item>
/// </list>
/// </summary>
public class Reservation : AuditableEntity
{
    private Reservation() { }

    private Reservation(
        Guid? driverId,
        Guid chargerId,
        Guid? vehicleId,
        DateTimeOffset startTime,
        DateTimeOffset endTime,
        decimal advanceDepositAmount)
    {
        DriverId = driverId;
        ChargerId = chargerId;
        VehicleId = vehicleId;
        StartTime = startTime;
        EndTime = endTime;
        AdvanceDepositAmount = advanceDepositAmount;
        Status = ReservationStatus.Pending;
    }

    // ── Identity ────────────────────────────────────────────────────────────
    public Guid Id { get; private set; }

    // ── Relationships ────────────────────────────────────────────────────────
    /// <summary>
    /// The registered driver who booked the slot.
    /// <c>null</c> for unregistered walk-in customers admitted by station staff.
    /// </summary>
    public Guid? DriverId { get; private set; }

    /// <summary>The physical charger unit being reserved.</summary>
    public Guid ChargerId { get; private set; }

    /// <summary>
    /// The driver's registered vehicle profile used to compute compatibility.
    /// Optional — walk-ins and some advance bookings may omit this.
    /// </summary>
    public Guid? VehicleId { get; private set; }

    // ── Slot window ──────────────────────────────────────────────────────────
    public DateTimeOffset StartTime { get; private set; }
    public DateTimeOffset EndTime { get; private set; }

    // ── QR token ─────────────────────────────────────────────────────────────
    /// <summary>
    /// Cryptographically signed token generated by the application layer after
    /// successful advance payment. Set to <c>null</c> for walk-ins
    /// because they check in immediately without presenting a QR code.
    /// </summary>
    public string? ReservationQRCode { get; private set; }

    // ── Payment ──────────────────────────────────────────────────────────────
    /// <summary>
    /// Amount deducted from the driver's wallet at booking time.
    /// Zero for walk-ins (cash is collected on-site by staff).
    /// </summary>
    public decimal AdvanceDepositAmount { get; private set; }

    // ── Status ───────────────────────────────────────────────────────────────
    public ReservationStatus Status { get; private set; }

    // ── Navigation properties (populated by EF Core) ─────────────────────────
    public User? Driver { get; private set; }
    public ICollection<ReservationStatusHistory> StatusHistory { get; private set; } = [];

    // ── Factory methods ──────────────────────────────────────────────────────

    /// <summary>
    /// Creates a standard advance reservation made by a registered driver (FR-3.1).
    /// The caller (application service) must have already deducted the deposit from
    /// the driver's wallet before calling this method.
    /// </summary>
    public static Reservation Create(
        Guid driverId,
        Guid chargerId,
        DateTimeOffset startTime,
        DateTimeOffset endTime,
        decimal advanceDepositAmount,
        Guid? vehicleId = null)
    {
        ValidateTimeWindow(startTime, endTime);

        if (advanceDepositAmount < 0)
            throw new ArgumentException("Advance deposit cannot be negative.", nameof(advanceDepositAmount));

        return new Reservation(driverId, chargerId, vehicleId, startTime, endTime, advanceDepositAmount);
    }

    /// <summary>
    /// Creates an on-site walk-in reservation initiated by station staff (FR-3.5).
    /// <c>DriverId</c> is <c>null</c> and the status advances to <c>CheckedIn</c>
    /// immediately because the customer is already physically present.
    /// </summary>
    public static Reservation CreateWalkIn(
        Guid chargerId,
        DateTimeOffset startTime,
        DateTimeOffset endTime)
    {
        ValidateTimeWindow(startTime, endTime);

        var reservation = new Reservation(
            driverId: null,
            chargerId: chargerId,
            vehicleId: null,
            startTime: startTime,
            endTime: endTime,
            advanceDepositAmount: 0m);

        // Walk-ins skip Pending/Confirmed — the charger is locked immediately.
        reservation.Status = ReservationStatus.CheckedIn;
        return reservation;
    }

    // ── State transitions ────────────────────────────────────────────────────

    /// <summary>
    /// Attaches the signed QR token generated by the application layer after
    /// payment confirmation (FR-3.2). Transitions status to <c>Confirmed</c>.
    /// </summary>
    public void ConfirmWithQrCode(string qrCode)
    {
        if (Status != ReservationStatus.Pending)
            throw new InvalidOperationException(
                $"Only Pending reservations can be confirmed. Current status: {Status}.");

        if (string.IsNullOrWhiteSpace(qrCode))
            throw new ArgumentException("QR code token is required.", nameof(qrCode));

        ReservationQRCode = qrCode.Trim();
        Status = ReservationStatus.Confirmed;
    }

    /// <summary>
    /// Marks the reservation as checked in after station staff validates the QR
    /// code. Transitions status from <c>Confirmed</c> to <c>CheckedIn</c>.
    /// </summary>
    public void CheckIn()
    {
        if (Status != ReservationStatus.Confirmed)
            throw new InvalidOperationException(
                $"Only Confirmed reservations can be checked in. Current status: {Status}.");

        Status = ReservationStatus.CheckedIn;
    }

    /// <summary>
    /// Cancels the reservation The caller is responsible for
    /// applying the refund policy on the driver's wallet.
    /// </summary>
    public void Cancel()
    {
        if (Status is ReservationStatus.CheckedIn or ReservationStatus.Completed)
            throw new InvalidOperationException(
                $"Cannot cancel a reservation with status: {Status}.");

        Status = ReservationStatus.Cancelled;
    }

    /// <summary>
    /// Marks the reservation as completed after the charging session has ended
    /// and the invoice is settled.
    /// </summary>
    public void Complete()
    {
        if (Status != ReservationStatus.CheckedIn)
            throw new InvalidOperationException(
                $"Only CheckedIn reservations can be completed. Current status: {Status}.");

        Status = ReservationStatus.Completed;
    }

    // ── Helpers ──────────────────────────────────────────────────────────────

    private static void ValidateTimeWindow(DateTimeOffset startTime, DateTimeOffset endTime)
    {
        if (startTime >= endTime)
            throw new ArgumentException("Start time must be earlier than end time.");

        if (startTime < DateTimeOffset.UtcNow.AddMinutes(-5)) // Allow up to 5 mins clock skew
            throw new ArgumentException("Reservation cannot be scheduled in the past.");

        var today = DateTimeOffset.UtcNow.Date;
        var maxAllowedDate = today.AddDays(2); // Start time must be before midnight the day after tomorrow
        if (startTime >= maxAllowedDate)
            throw new ArgumentException("Reservations can only be made for today or tomorrow.");
    }
}
