/** @type {import('tailwindcss').Config} */
const inter = ['Inter', 'ui-sans-serif', 'system-ui', '-apple-system', 'Segoe UI', 'Roboto', 'sans-serif']

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        // Product accent — teal -> green
        brand: {
          DEFAULT: '#0EA5A0',
          from: '#0EA5A0',
          to: '#22C55E',
          50: '#ecfdf9',
          100: '#d0faf0',
          200: '#a3f3e1',
          300: '#6de6d0',
          400: '#38d1ba',
          500: '#0EA5A0',
          600: '#0c8481',
          700: '#0f6968',
          800: '#115453',
          900: '#123f3f',
        },

        // Dark "charcoal" surfaces — used by the auth / sign-in atmosphere panel
        ink: {
          DEFAULT: '#0F1115',
          950: '#0B0D10',
          900: '#0F1115',
          800: '#131720',
          700: '#161920',
          600: '#1F2430',
          500: '#232936',
          400: '#2D333F',
          300: '#3A4150',
        },

        // Material 3 design tokens (used by the marketing / landing page)
        background: '#f9f9ff',
        'on-background': '#1a1c20',
        surface: '#f9f9ff',
        'surface-bright': '#f9f9ff',
        'surface-dim': '#d9d9df',
        'surface-tint': '#006a61',
        'surface-variant': '#e2e2e8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f3f9',
        'surface-container': '#ededf3',
        'surface-container-high': '#e8e8ed',
        'surface-container-highest': '#e2e2e8',
        'on-surface': '#1a1c20',
        'on-surface-variant': '#3d4947',
        'inverse-surface': '#2f3035',
        'inverse-on-surface': '#f0f0f6',
        'inverse-primary': '#6bd8cb',
        primary: '#00685f',
        'on-primary': '#ffffff',
        'primary-container': '#008378',
        'on-primary-container': '#f4fffc',
        'primary-fixed': '#89f5e7',
        'primary-fixed-dim': '#6bd8cb',
        'primary-fixed-variant': '#005049',
        'on-primary-fixed': '#00201d',
        'on-primary-fixed-variant': '#005049',
        secondary: '#006398',
        'on-secondary': '#ffffff',
        'secondary-container': '#5bb8fe',
        'on-secondary-container': '#00476e',
        'secondary-fixed': '#cce5ff',
        'secondary-fixed-dim': '#93ccff',
        'on-secondary-fixed': '#001d31',
        'on-secondary-fixed-variant': '#004b73',
        tertiary: '#006947',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#00855b',
        'on-tertiary-container': '#f5fff6',
        'tertiary-fixed': '#6ffbbe',
        'tertiary-fixed-dim': '#4edea3',
        'on-tertiary-fixed': '#002113',
        'on-tertiary-fixed-variant': '#005236',
        outline: '#6d7a77',
        'outline-variant': '#bcc9c6',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
      },
      backgroundImage: {
        'brand-gradient': 'linear-gradient(135deg, #0EA5A0 0%, #22C55E 100%)',
      },
      fontFamily: {
        sans: inter,
        'display-lg': inter,
        'display-lg-mobile': inter,
        'headline-lg': inter,
        'headline-md': inter,
        'headline-sm': inter,
        'body-lg': inter,
        'body-md': inter,
        'body-sm': inter,
        'label-md': inter,
        'label-sm': inter,
        'metric-num-lg': inter,
        'metric-num-md': inter,
      },
      fontSize: {
        'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.025em', fontWeight: '600' }],
        'display-lg-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-sm': ['16px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', letterSpacing: '0em', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '600' }],
        'metric-num-lg': ['32px', { lineHeight: '38px', letterSpacing: '-0.03em', fontWeight: '600' }],
        'metric-num-md': ['20px', { lineHeight: '26px', letterSpacing: '-0.02em', fontWeight: '600' }],
      },
      spacing: {
        'space-2xs': '0.125rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '0.75rem',
        'space-lg': '1rem',
        'space-xl': '1.5rem',
        'space-2xl': '2rem',
        'space-3xl': '3rem',
        'gutter-mobile': '1rem',
        'gutter-desktop': '1.5rem',
        'sidebar-width': '260px',
        'topbar-height': '64px',
      },
      ringColor: {
        brand: '#0EA5A0',
      },
      animation: {
        'pulse-slow': 'pulse 5s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'float-slow': 'float 7s ease-in-out infinite',
        'spin-slow': 'spin 24s linear infinite',
        glow: 'glow 4s ease-in-out infinite alternate',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        glow: {
          '0%': { opacity: '0.4', transform: 'scale(0.98)' },
          '100%': { opacity: '0.75', transform: 'scale(1.05)' },
        },
      },
    },
  },
  plugins: [],
}
