name: Mobile CI

on:
  push:
    branches: [ "dev" ]
    paths:
      - 'mobile-flutter/**'
  pull_request:
    branches: [ "dev" ]
    paths:
      - 'mobile-flutter/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mobile-flutter

    steps:
    - uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.47.5'
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Verify formatting
      run: dart format --output=none --set-exit-if-changed .

    - name: Analyze project source
      run: flutter analyze

    - name: Run tests
      run: flutter test
